Feature/messaging common
extreal-dev/Extreal.Integration.Messaging pull request #1
Opened 2023-12-18 02:29 UTC by mahaweilu

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-12-27 05:37 UTC, sus-yoshikane-t requested changes

2023-12-27 05:37 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Messaging.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
こちら残っていてよいのでしょうか？

2023-12-27 05:37 UTC, sus-yoshikane-t commented on Runtime/MessagingClient.cs
> +        protected void SetJoiningGroupStatus(bool isJoinedGroup)
メソッド名だけJoiningなのが気になりました(StatusがついたりIsがなかったりしているので意図したものなら問題ないです)

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// Whether this client is joined a group or not.
Whether this client has joined a group or notはどうですか？isJoinedもhasJoinedGroupに

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// <para>Invokes immediately after this client joins a group.</para>
joins -> joined　だと思います

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// <para>Invokes immediately after a user joins the group this client joined.</para>
after a user joined in the same group.はどうですか？

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// Arg: ID of the user sending the message and the message.
and the message　-> the message contentはどうですか？

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/MessagingJoiningConfig.cs
> +    public class MessagingJoiningConfig
悩みますが、messagingは受送信のやりとりということで、messagingConfigかmessagingConnectionConfigが良いと思いますがどうですか？MessagingJoiningConfigは「受送信のやりとりに入室/参加の設定」という雰囲気が強いかと考えています。

2023-12-27 09:04 UTC, mahaweilu commented on Runtime/QueuingMessagingClient.cs
> +        /// Whether this client is joined a group or not.
同じく、has joinedが良いと思います。

2023-12-27 10:55 UTC, sasuke9410 reviewed
他の人と重複した指摘には 👍 マークを付けています

2024-01-09 05:04 UTC, mahaweilu commented on Runtime/MessagingJoiningConfig.cs
> +    public class MessagingJoiningConfig
MessagingJoiningConfigにした理由：
１．Joinメソッドに渡すもので、messagingConfigかmessagingConnectionConfigだと意味合いが合わない
２．constructorで渡すならmessagingConfigが良い

2024-01-09 05:06 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// Arg: ID of the user sending the message and the message.
以下の理由で対応不要とします。
メッセージのそのものなのでシンプルで良い

2024-01-09 05:08 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        protected void SetJoiningGroupStatus(bool isJoinedGroup)
以下の理由で対応不要とします。

「参加しようとしてるグループに対して参加済みかどうか」のため、意図したのもです。

2024-01-09 05:12 UTC, mahaweilu commented on Runtime/Extreal.Integration.Messaging.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
不要なので削除しました。

[59b95fa](https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1/commits/59b95fa2d4b82013762c2052f736d689526eb093)

2024-01-09 05:13 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// <para>Invokes immediately after this client joins a group.</para>
fixed 
[6d58168](https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1/commits/6d5816805f4eedee5780110633ee73f932394b45)

2024-01-09 05:13 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// <para>Invokes immediately after a user joins the group this client joined.</para>
fixed [6d58168](https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1/commits/6d5816805f4eedee5780110633ee73f932394b45)

2024-01-09 05:14 UTC, mahaweilu commented on Runtime/QueuingMessagingClient.cs
> +        /// Whether this client is joined a group or not.
fixed [6d58168](https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1/commits/6d5816805f4eedee5780110633ee73f932394b45)

2024-01-09 05:16 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// Whether this client is joined a group or not.
docのみ修正しました。過去ライブラリにisXXXの命名が主流のため、isJoinedはそのままにします。
[6d58168](https://github.com/extreal-dev/Extreal.Integration.Messaging.Common/pull/1/commits/6d5816805f4eedee5780110633ee73f932394b45)

2024-01-09 08:25 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Messaging.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
CIで検知できるようになっていて、マージ前に削除するそうなので、申し訳ありませんが元に戻していただくようお願いします。

2024-01-09 08:29 UTC, sus-yoshikane-t commented on Runtime/MessagingClient.cs
> +        protected void SetJoiningGroupStatus(bool isJoinedGroup)
分かりました。

2024-01-09 08:46 UTC, mahaweilu commented on Runtime/Extreal.Integration.Messaging.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
戻しました。
[93f02e4](https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/1/commits/93f02e41becbd1567368bec2fe2d52c107a79a38)

2024-01-09 09:18 UTC, sus-yoshikane-t commented on Runtime/Extreal.Integration.Messaging.Common.asmdef
> +        "Extreal.SampleApp.Holiday.Analyzer",
確認しました。

2024-01-16 08:59 UTC, kiyohome approved these changes

2024-01-18 01:40 UTC, sus-yoshikane-t approved these changes

2024-01-18 01:42 UTC, merged