remove create/delete group and refactoring
extreal-dev/Extreal.Integration.Messaging pull request #3
Opened 2024-01-23 08:55 UTC by mahaweilu

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-01-26 09:23 UTC, kiyohome requested changes

2024-01-26 09:23 UTC, kiyohome commented on Runtime/MessagingJoiningConfig.cs
> +        public int MaxCapacity { get; }
MaxCapacityはこのモジュールで使わないので、ここで保持すべきでないと思います。
どうしてここに保持してるんですか？

2024-01-26 10:46 UTC, kiyohome requested changes

2024-01-26 10:46 UTC, kiyohome commented on Runtime/MessagingClient.cs
> +        /// IDs of joined clients.
IsJoinedGroupは何に使ってますか？

2024-01-29 07:00 UTC, mahaweilu commented on Runtime/MessagingJoiningConfig.cs
> +        public int MaxCapacity { get; }
>どうしてここに保持してるんですか？
特に強い理由がないのですが修正前にこのモジュール内のGroupConfig.csに保持していためです。

2024-01-29 07:19 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// IDs of joined clients.
以下MultiplayClient.csでクライアントがjoinedかどうかを見て同期開始の判別処理で使われています。

https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging/blob/53ba7daaf8a747b29a7d34d8c777810c5504bb64/Runtime/MultiplayClient.cs#L186

2024-01-29 09:29 UTC, mahaweilu commented on Runtime/MessagingClient.cs
> +        /// IDs of joined clients.
必要性

2024-01-29 09:31 UTC, mahaweilu commented on Runtime/MessagingJoiningConfig.cs
> +        public int MaxCapacity { get; }
シンプル最小限

2024-01-31 02:56 UTC, sus-yoshikane-t commented on Runtime/MessagingClient.cs
> +        /// IDs of joined clients.
メモ：OnJoined等を使って不要にならないか確認する

2024-02-02 00:26 UTC, sus-yoshikane-t commented on Runtime/MessagingJoiningConfig.cs
> +        public int MaxCapacity { get; }
修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/3/commits/29c97de75acd0cf4c85a43c7ae993025c51e97ff

2024-02-02 01:34 UTC, sus-yoshikane-t commented on Runtime/MessagingClient.cs
> +        /// IDs of joined clients.
MultiplayClientの`OnJoined`, `OnLeaving`, `OnUnexpectedLeft`を使用して判定するように修正しました。https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/3/commits/880e885691bd8ce14b10b0aafd38e994362f4225

2024-02-02 05:30 UTC, kiyohome approved these changes

2024-02-02 05:30 UTC, merged